# Generated by Django 4.0.2 on 2022-04-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
